security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AB\CustomerPortalBundle\Entity\User: plaintext

    providers:
        db_provider:
            entity:
                class: CustomerPortalBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: secutity.login
                check_path: secutity.login
                default_target_path: portal.admin

            pattern: ^/
            provider: db_provider

            logout:
                path: /logout
                target: /

    access_control:
            - { path: ^/portal, roles: ROLE_USER }
            - { path: ^/portal/*, roles: ROLE_USER }
