portal.index:
    path:     /
    defaults: { _controller: CustomerPortalBundle:Portal:index }

portal.portal:
    path:     /portal
    defaults: { _controller: CustomerPortalBundle:Portal:portal }

secutity.login:
    path:     /login
    defaults: { _controller: CustomerPortalBundle:Security:login }

secutity.logout:
    path:     /logout

portal.ajax.get-passengers:
    path:     /portal/get-passengers.ajax
    defaults: { _controller: CustomerPortalBundle:PortalAjax:getPassengers }
    methods: GET

portal.ajax.add-passenger:
    path:     /portal/add-passenger.ajax
    defaults: { _controller: CustomerPortalBundle:PortalAjax:addPassenger }
    methods: POST

portal.ajax.del-passenger:
    path:     /portal/del-passenger.ajax/{id}
    defaults: { _controller: CustomerPortalBundle:PortalAjax:delPassenger }
    methods: DELETE
